<?php

namespace AppBundle\Repository;

/**
 * UserNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
